### ISSUE TITLE
After a week in use it uses a lot of hdd space (Cache)

### ISSUE THREAD

**Issue by Baklap4** [ai-traders/liget#1]
At first thanks for making this! We can now host our packages within a nuget server on linux, love it!

But after a week in use (within docker) i came to the knowledge it was holding like 15Gb of cache in the `/tmp` folder.
What would be a way to clean this automaticly (after a limit has been hit?)
I now cleaned it myself by removing the `/tmp/NuGet/TempCache/` folder since it gets recreated.

![image](https://user-images.githubusercontent.com/3918517/34822130-25ed24ae-f6c6-11e7-931e-011d34bbe9f9.png)
It's already at 1.7GB again..

**Comment by tomzo** [comment]
Hi,

Thanks for reporting this. Our server runs on k8s and gets restarted once in a while so `/tmp` gets deleted periodically, so we did not notice so far.
I took a quick look why `/tmp/NuGet/TempCache/` would grow indefinitely. By the contents and timestamps I guess this created by [NuGet.CatalogReader](https://github.com/emgarten/NuGet.CatalogReader) when it downloads recent changes from nuget.org.
But let me understand the problem better, are you using liget as 
 * host for private packages 
 * or as cache
 * or both? 

This is definitely a bug, I think those folders should be cleaned up immediately.

**Comment by Baklap4** [comment]
> But let me understand the problem better, are you using liget as
host for private packages or as cache or both?

Currently i'm using liget as a host for private packages. I started up the docker file with default values.

**Comment by tomzo** [comment]
I've sent a fix. There should be a release soon after all tests pass.

**Comment by Baklap4** [comment]
Thanks a lot ^^ Just upgraded 👍
