### ISSUE TITLE
Define port in environments

### ISSUE THREAD

**Issue by cobraz** [ai-traders/liget#12]
Hello 👋

We are using Liget – and we use Google App Engine. The problem is that App Engine requires us to use port 8080 for the load balancer. Right now, we just use the instance ip to communicate with Liget on port 9011. It would be super nice to be able to dynamically set that port.

We use a Dockerfile that looks like this:
 ```
FROM tomzo/liget:1.0.1

EXPOSE 9011
```

Maybe we could add a `ENV` to this?

**Comment by tomzo** [comment]
Makes sense, currently it is hardcoded in https://github.com/ai-traders/liget/blob/master/src/LiGet/Program.cs#L106

It could be parameterized with `LIGET_LISTEN_PORT`, defaulting to 9011

**Comment by hmol** [comment]
👋  @tomzo take a look at my pull request. I think I have solved this issue.

**Comment by tomzo** [comment]
@hmol thanks for the PR. It is released in 1.0.2
