### ISSUE TITLE
Azure Container Instances: persist?

### ISSUE THREAD

**Issue by katlimruiz** [ai-traders/liget#7]
This may be a newbie question, I'm new to docker and all the containerization hype, so I'm trying to setup this in Azure Container Instances.

I manage to create one successfully, and be able to open the website as "mywebnuget.eastus.azurecontainer.io:9011".

However, when I restart the container, it removes all the packages I uploaded. This seems to be because there are no volumes assigned.

In your readme says to use:
```
mkdir -p /tmp/liget-test
docker run -p 9011:9011 -v /tmp/liget-test/:/data tomzo/liget
```

However, in ACI I cannot "customize" the run command, so how can I add this volume or command before running the container?

Probably you'll tell me dont use ACI ha ha, but I want to give it a try.

**Comment by tomzo** [comment]
Yep, azure files seems as the right way in this case.
See https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files

**Comment by tomzo** [comment]
@ElanHasson dbreeze is used only before 1.0.0 and yes, locking is quite an issue there.

**Comment by ElanHasson** [comment]
That is welcome news!
